"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  NicknameProvider,
  UserStoreProvider,
  WebSocketProvider,
} from "../src/providers";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Turborepo",
//   description: "Generated by create turbo",
// };

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserStoreProvider>
          <WebSocketProvider>
            <QueryClientProvider client={queryClient}>
              <NicknameProvider>{children}</NicknameProvider>
            </QueryClientProvider>
          </WebSocketProvider>
        </UserStoreProvider>
      </body>
    </html>
  );
}
