'use client'

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserStoreProvider, WebSocketProvider } from "../src/providers";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Turborepo",
//   description: "Generated by create turbo",
// };

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  console.log("RootLayout Rendering");
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserStoreProvider>
          <WebSocketProvider>
            <QueryClientProvider client={queryClient}>
              {children}
            </QueryClientProvider>
          </WebSocketProvider>
        </UserStoreProvider>
      </body>
    </html>
  );
}
